### ISSUE TITLE
add per __rulefile_name__ metrics for prometheus_evaluator_duration_seconds

### ISSUE THREAD

**Issue by tamsky** [tamsky/prometheus#1]
Relates to upstream issues #1315, #912.

fabxc writes in :

> +1 for the more detailed reporting – especially those feeding into metrics.

Having metrics would seem to be even more helpful than the proposed slow query logging.

If we don't have a way to track historical duration metrics for our existing rulesets,
we don't have a good way to track and correlate what might be causing them to change.

Proposed Enhancement:

`prometheus_evaluator_duration_seconds`  would gain a per-rulefile attribution for its duration metrics, the names of the rulefiles for attributed rules would be the differentiating labels.

Existing:

```
...
prometheus_evaluator_duration_seconds{quantile="0.99"} 28.723547622
prometheus_evaluator_duration_seconds_sum 1.2975980708410116e+06
prometheus_evaluator_duration_seconds_count 82090
```

Proposed:

```
prometheus_evaluator_duration_seconds{quantile="0.99"} 28.723547622
prometheus_evaluator_duration_rulefile_seconds{path="rules/file1.rules"} 16.723547622
prometheus_evaluator_duration_rulefile_seconds{path="rules/file2.rules"} 12.000000000
prometheus_evaluator_duration_seconds_sum 1.2975980708410116e+06
prometheus_evaluator_duration_seconds_count 82090
```

**Comment by tamsky** [comment]
- [ ] Add a new `RuleFileNameLabel` to https://github.com/prometheus/prometheus/blob/e83f05fe93c32c9e808b2a6a907337b442a540dc/vendor/github.com/prometheus/common/model/labels.go
- [ ] Create new vector metric `prometheus_evaluator_duration_seconds`
- [ ] set `RuleFileNameLabel` on each rule during load at:
  https://github.com/prometheus/prometheus/blob/273e457da4ec971c658282f1869bd54e24b962fc/rules/manager.go#L463
- [ ] Increment `prometheus_evaluator_duration_seconds` stat at https://github.com/prometheus/prometheus/blob/273e457da4ec971c658282f1869bd54e24b962fc/rules/manager.go#L257 with label `path=$RuleFileNameLabel`

**Comment by mrwacky42** [comment]
+1

**Comment by tamsky** [comment]
Closed by https://github.com/prometheus/prometheus/pull/3491

**Comment by tamsky** [comment]
And by https://github.com/prometheus/prometheus/pull/3527
